# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zL22lgi7X7YjXcjZ5HcatY3b0wGyTn3t
"""

from google.colab import files
files.upload()

import os

os.makedirs('/root/.kaggle', exist_ok=True)

!cp kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!pip install -q kaggle

!kaggle datasets download -d 'shivamb/netflix-shows'

!unzip netflix-shows.zip

!ls

import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

features = [
    'release_year',
    'rating',
    'country'
]

data = df[['type','release_year','rating','country']]
data.head()

data.isnull().sum()
data['country'] = data['country'].fillna('Unknown')
data['rating'] = data['rating'].fillna('Unknown')

data.isnull().sum()

data.head()

from sklearn.preprocessing import LabelEncoder

le_type = LabelEncoder()
le_rating = LabelEncoder()
le_country = LabelEncoder()

data['type'] = le_type.fit_transform(data['type'])
data['rating'] = le_rating.fit_transform(data['rating'])
data['country'] = le_country.fit_transform(data['country'])

data.head()

X = data.drop('type', axis=1)
y = data['type']

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

data['type'].value_counts()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

data = df[['type',
           'release_year',
           'rating',
           'country',
           'duration',
           'listed_in']].copy()

data.fillna('Unknown', inplace=True)

data['duration_num'] = data['duration'].str.extract(r'(\d+)')

data['duration_num'] = data['duration_num'].fillna(0)

data['duration_num'] = data['duration_num'].astype(int)

print(data[['duration', 'duration_num']].head(10))

data['duration'].isnull().sum()

data['main_genre'] = data['listed_in'].str.split(',').str[0]

data[['listed_in', 'main_genre']].head()

data.drop(['duration', 'listed_in'], axis=1, inplace=True)

print(data.columns)

data.isnull().sum()

data = pd.get_dummies(
    data,
    columns=['rating', 'country', 'main_genre']
)

print(data.shape)
data.head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data['type'] = le.fit_transform(data['type'])

print(le.classes_)

X = data.drop('type', axis=1)
y = data['type']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

from sklearn.metrics import accuracy_score

print("Random Forest :", accuracy_score(y_test, rf_pred))

from sklearn.metrics import classification_report

print(classification_report(y_test, rf_pred))

df.groupby('type')['duration'].head(10)

import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df.head()

df['rating'] = df['rating'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

df['duration_num'] = df['duration'].str.extract(r'(\d+)')
df['duration_num'] = df['duration_num'].fillna(0).astype(int)
df['main_genre'] = df['listed_in'].str.split(',').str[0]

X = df[['duration_num', 'rating', 'country']]
y = df['release_year']

from sklearn.preprocessing import LabelEncoder

le_rating = LabelEncoder()
le_country = LabelEncoder()

X['rating'] = le_rating.fit_transform(X['rating'])
X['country'] = le_country.fit_transform(X['country'])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("MAE:",mae)

from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(y_test,y_pred)
print("RMSE:",rmse)