# -*- coding: utf-8 -*-
"""Practice_day8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E0hOxC8eL16DrkwhuAR84laEXaFRL4D
"""

arr = list(map(int, input().split()))

f = s = arr[0]

for i in range(len(arr)):
    if arr[i] > f:
        s = f
        f = arr[i]
    elif arr[i] > s:
        s = arr[i]
print("Second largest:", s)

s = input()
for ch in s:
  if s.count(ch) == 1:
    print(ch)
    break

arr = list(map(int, input().split()))
k = int(input())

k = k % len(arr)

arr = arr[-k:] + arr[:-k]

print(arr)

num = list(map(int, input().split()))
even = []
odd = []
for i in num:
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)

result = even + odd

print(result)

nested_list = [[1, 2, 3], [4, 5], [6, 7, 8]]
total = 0
for i in nested_list:
    for num in i:
        total += num

print(total)

n = int(input())

for num in range(1, n + 1):
    temp = num
    digit_sum = 0
    digit_product = 1

    while temp > 0:
        digit = temp % 10
        digit_sum += digit
        digit_product *= digit
        temp //= 10

    if digit_sum == digit_product:
        print(num)

arr = list(map(int, input().split()))
target = int(input())

for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] + arr[j] == target:
            print(arr[i], arr[j])

n = "education"
vowels = "aeiou"

consonants = []

for ch in n:
    if ch.isalpha() and ch not in vowels:
        consonants.append(ch)
print("Consonants:", consonants)
print("Length:", len(consonants))