# -*- coding: utf-8 -*-
"""Sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIJWl9VGE4xPypUCtf8IltPk60NdqWU1
"""

arr = [5,3,8,1,2]
n = len(arr)
for i in range(n):
  for j in range(n-1-i):
    if arr[j] > arr[j+1]:
      arr[j],arr[j+1] = arr[j+1],arr[j]
print(arr)

def selection_sort(arr):
  n = len(arr)
  for i in range(n):
    min = i
    for j in range(i+1,n):
      if arr[j] < arr[min]:
        min = j
    arr[i],arr[min] = arr[min],arr[i]
  return arr

print(selection_sort([64,25,12,22,11]))

def insertion_sort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    j = i-1
    while j>=0 and arr[i]>key :
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
  return arr
print(selection_sort([5,4,3,2]))

def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2

    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    return merge(left, right)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])

    return result

arr = list(map(int, input("Enter elements: ").split()))
sorted_arr = merge_sort(arr)
print("Sorted array:", *sorted_arr)

n = int(input())

for i in range(n):
    c = 1
    for j in range(i + 1):
        print(c, end="")
        c = c * (i - j) // (j + 1)
    print()