# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnzsWgivsgYMwxHarHlRNFETJvhMkOfL
"""

from google.colab import files
files.upload()

import os

os.makedirs('/root/.kaggle', exist_ok=True)

!cp kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!pip install -q kaggle

!kaggle datasets download -d spscientist/students-performance-in-exams

!unzip students-performance-in-exams.zip

import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")

df['Pass'] = (df['math score'] >= 40).astype(int)

X = df.drop('Pass', axis=1)
y = df['Pass']

from sklearn.preprocessing import LabelEncoder

for col in X.select_dtypes(include='object').columns:
    X[col] = LabelEncoder().fit_transform(X[col])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.svm import SVC

model = SVC(kernel='rbf')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("StudentsPerformance.csv")

print(df.head())
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())

sns.countplot(x='gender', data=df)
plt.show()

sns.countplot(x='race/ethnicity', data=df)
plt.show()

sns.countplot(x='parental level of education', data=df)
plt.xticks(rotation=45)
plt.show()

sns.countplot(x='lunch', data=df)
plt.show()

sns.countplot(x='test preparation course', data=df)
plt.show()

sns.histplot(df['math score'], kde=True)
plt.show()

sns.histplot(df['reading score'], kde=True)
plt.show()

sns.histplot(df['writing score'], kde=True)
plt.show()

sns.boxplot(data=df[['math score','reading score','writing score']])
plt.show()

sns.heatmap(df[['math score','reading score','writing score']].corr(), annot=True)
plt.show()

df['Pass'] = (df['math score'] >= 40).astype(int)

X = df.drop('Pass', axis=1)
y = df['Pass']

from sklearn.preprocessing import LabelEncoder

for col in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.svm import SVC

model = SVC(kernel='rbf')

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')
plt.show()